=pod

=encoding utf-8

=head1 NAME

Meh - Moo, purloined sugar, defaults

=head1 SYNOPSIS

    use Meh;
    
    ro onetwothree => 123;
    lazy onetwothreebytwo => sub( $self ) { $self->onetwothree * 2 };
    
    rwp flag => 1;
    rw volatile => 0,
       required => 1,
       coerce => sub( $val ) { !!$val };
    
    ro log => undef,
       required => 1,
       isa => FileHandle;

=head1 DESCRIPTION

Meh imports Moo with shorthand and handy defaults.

=head1 SEE ALSO

=over
 
=item *
 
L<MooX::ShortHas>

=item *

L<Mew>

=back

=cut
