=pod

=encoding utf-8

=head1 NAME

Meh - Moo, purloined sugar, defaults

=head1 SYNOPSIS

    use Meh;
    
    ro onetwothree => 123;
    lazy onetwothreebytwo => sub( $self ) { $self->onetwothree * 2 };
    
    rwp flag => 1;
    rw volatileflag => 0,
       coerce => sub( $val ) { !!$val };
    
    required log => isa => FileHandle;
    
    instance loop => 'IO::Async::Loop';
    instance json => 'JSON::MaybeXS', utf8 => 1;
    
    singleton logger => 'My::Logger', verbose = WARN;

=head1 DESCRIPTION

Meh imports Moo with shorthand and handy defaults.

=head1 SEE ALSO

=over
 
=item *
 
L<MooX::ShortHas>

=item *

L<Mew>

=back

=cut
